version: '3.8'
services:
  farmakariyer:
    image: ${DOCKER_REGISTRY-}farmakariyer
    build:
      context: .
      dockerfile: WebUI/Dockerfile
    container_name: farmakariyer
    ports:
      - "6100:80"
    environment:
      - TZ=Europe/Istanbul
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    restart: unless-stopped